### ISSUE TITLE
My reply broke your note display

### ISSUE THREAD

**Issue by myfreeweb** [jonnybarnes/jonnybarnes.uk#51]
https://unrelenting.technology/replies/2017-05-20-22-49-20 → https://jonnybarnes.uk/notes/Dr "Whoops, looks like something went wrong."

<img width="756" alt="2017-05-21 01_53_08-nightly" src="https://cloud.githubusercontent.com/assets/208340/26279860/4a28f3b4-3dc8-11e7-8133-fed9b1df2693.png">

sorry :D

**Comment by jonnybarnes** [comment]
Hey Greg, so looking at my error logs, the issue I have is I use a package called Carbon to deal with time/dates. And the published time that I’ve retreived from your reply is `2017-05-20T22:49:20.652843318Z`. This then chokes up Carbon:

```
>>> $carbon->parse('2017-05-20T22:49:20.652843318Z')->toDayDateTimeString();
Exception with message 'DateTime::__construct(): Failed to parse time string (2017-05-20T22:49:20.652843318Z) at position 0 (2): The timezone could not be found in the database'
```

So I’m not sure what to do?

**Comment by myfreeweb** [comment]
omg, *another* PHP DateTime issue? (the WordPress IndieWeb plugins suite was displaying my dates as 1969 :D)

For now you could catch the exception and retry parsing as Atom format explicitly I guess.

**Comment by jonnybarnes** [comment]
“fixed” in v0.5.8

quotes because as you suggest, I catch the exception and then fallback to using the time my app saved the reply

**Comment by myfreeweb** [comment]
Cool.

BTW, you version your personal site's code already? wow. I haven't released a single named version of https://github.com/myfreeweb/sweetroll yet :D

**Comment by jonnybarnes** [comment]
yeah, the plan is that when I get to v1.0 someone else in theory could just git clone, edit come config values and use it themself.
